# Generated by Django 5.0.1 on 2025-09-19 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('pal_request', 'Recovery Pal Request'), ('pal_accepted', 'Pal Request Accepted'), ('message', 'New Message'), ('follow', 'New Follower'), ('sponsor_request', 'Sponsor Request'), ('sponsor_accepted', 'Sponsor Request Accepted'), ('challenge_invite', 'Challenge Invitation'), ('challenge_pal', 'Challenge Pal Request'), ('milestone', 'Milestone Achievement'), ('group_invite', 'Group Invitation'), ('comment', 'New Comment'), ('like', 'New Like')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=500)),
                ('object_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'is_read'], name='accounts_no_recipie_8b48cc_idx'), models.Index(fields=['created_at'], name='accounts_no_created_caf92d_idx')],
            },
        ),
    ]
