# Generated by Django 5.0.1 on 2025-10-09 11:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invite_only_mode', models.BooleanField(default=True, help_text='When enabled, registration requires an invite code')),
                ('waitlist_enabled', models.BooleanField(default=True, help_text='When enabled, users can request access via waitlist')),
                ('waitlist_message', models.TextField(default="We're currently in beta! Request access to join our community.", help_text='Message shown to users on the waitlist page')),
                ('registration_closed_message', models.TextField(default='Registration is currently closed. Please check back later!', help_text='Message shown when both invite mode and waitlist are disabled')),
                ('auto_approve_waitlist', models.BooleanField(default=False, help_text='Automatically approve all waitlist requests')),
                ('max_users', models.IntegerField(blank=True, help_text='Maximum number of registered users (optional limit)', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='InviteCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('email', models.EmailField(blank=True, help_text='If specified, only this email can use the code', max_length=254, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Leave blank for no expiration', null=True)),
                ('max_uses', models.IntegerField(default=1, help_text='Number of times this code can be used')),
                ('uses_remaining', models.IntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invite_codes', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invite_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invite Code',
                'verbose_name_plural': 'Invite Codes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaitlistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(blank=True, max_length=50)),
                ('reason', models.TextField(blank=True, help_text='Why do you want to join MyRecoveryPal?')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, help_text='How did you hear about us?', max_length=100)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_waitlist_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Waitlist Request',
                'verbose_name_plural': 'Waitlist Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
