# Generated by Django 5.2.4 on 2025-09-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_activityfeed_activitycomment_dailycheckin'),
        ('accounts', '0003_activity_feed'),
    ]

    operations = [
    ]
