# Generated by Django 5.0.10 on 2025-11-14 15:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_systemsettings_invitecode_waitlistrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(
                    choices=[('free', 'Free'), ('premium', 'Premium'), ('pro', 'Professional')],
                    default='free',
                    max_length=10
                )),
                ('status', models.CharField(
                    choices=[
                        ('active', 'Active'),
                        ('past_due', 'Past Due'),
                        ('canceled', 'Canceled'),
                        ('unpaid', 'Unpaid'),
                        ('trialing', 'Trialing'),
                        ('incomplete', 'Incomplete')
                    ],
                    default='active',
                    max_length=20
                )),
                ('billing_period', models.CharField(
                    blank=True,
                    choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')],
                    max_length=10,
                    null=True
                )),
                ('stripe_customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255, null=True)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('trial_end', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='subscription',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'indexes': [
                    models.Index(fields=['user'], name='subscriptions_user_idx'),
                    models.Index(fields=['stripe_customer_id'], name='subscriptions_stripe_customer_idx'),
                    models.Index(fields=['stripe_subscription_id'], name='subscriptions_stripe_subscription_idx'),
                    models.Index(fields=['status'], name='subscriptions_status_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tier', models.CharField(
                    choices=[('free', 'Free'), ('premium', 'Premium'), ('pro', 'Professional')],
                    max_length=10
                )),
                ('billing_period', models.CharField(
                    choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')],
                    max_length=10
                )),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_price_id', models.CharField(blank=True, max_length=255)),
                ('stripe_product_id', models.CharField(blank=True, max_length=255)),
                ('features', models.JSONField(blank=True, default=list)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Subscription Plan',
                'verbose_name_plural': 'Subscription Plans',
                'db_table': 'subscription_plans',
                'ordering': ['sort_order', 'tier', 'billing_period'],
                'unique_together': {('tier', 'billing_period')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(
                    choices=[
                        ('subscription', 'Subscription Payment'),
                        ('one_time', 'One-time Payment'),
                        ('refund', 'Refund')
                    ],
                    default='subscription',
                    max_length=20
                )),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('succeeded', 'Succeeded'),
                        ('failed', 'Failed'),
                        ('refunded', 'Refunded'),
                        ('canceled', 'Canceled')
                    ],
                    default='pending',
                    max_length=20
                )),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_charge_id', models.CharField(blank=True, max_length=255, null=True)),
                ('stripe_invoice_id', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True)),
                ('payment_method_last4', models.CharField(blank=True, max_length=4)),
                ('payment_method_brand', models.CharField(blank=True, max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='transactions',
                    to=settings.AUTH_USER_MODEL
                )),
                ('subscription', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='transactions',
                    to='accounts.subscription'
                )),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['user', '-created_at'], name='transactions_user_created_idx'),
                    models.Index(fields=['stripe_payment_intent_id'], name='transactions_stripe_payment_idx'),
                    models.Index(fields=['status'], name='transactions_status_idx'),
                ],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_payment_method_id', models.CharField(max_length=255, unique=True)),
                ('card_brand', models.CharField(blank=True, max_length=20)),
                ('card_last4', models.CharField(blank=True, max_length=4)),
                ('card_exp_month', models.IntegerField(blank=True, null=True)),
                ('card_exp_year', models.IntegerField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='payment_methods',
                    to=settings.AUTH_USER_MODEL
                )),
            ],
            options={
                'verbose_name': 'Payment Method',
                'verbose_name_plural': 'Payment Methods',
                'db_table': 'payment_methods',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_invoice_id', models.CharField(max_length=255, unique=True)),
                ('stripe_invoice_pdf', models.URLField(blank=True)),
                ('status', models.CharField(
                    choices=[
                        ('draft', 'Draft'),
                        ('open', 'Open'),
                        ('paid', 'Paid'),
                        ('void', 'Void'),
                        ('uncollectible', 'Uncollectible')
                    ],
                    default='open',
                    max_length=20
                )),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('invoice_date', models.DateTimeField()),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='invoices',
                    to=settings.AUTH_USER_MODEL
                )),
                ('subscription', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='invoices',
                    to='accounts.subscription'
                )),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'db_table': 'invoices',
                'ordering': ['-invoice_date'],
                'indexes': [
                    models.Index(fields=['user', '-invoice_date'], name='invoices_user_invoice_idx'),
                    models.Index(fields=['stripe_invoice_id'], name='invoices_stripe_invoice_idx'),
                ],
            },
        ),
    ]
