# Generated by Django 5.0.10 on 2025-11-16 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_subscription_payment_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Share your thoughts, wins, or encouragement",
                        max_length=1000,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="social_posts/"),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Everyone"),
                            ("friends", "Friends Only"),
                            ("private", "Only Me"),
                        ],
                        default="public",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Social Post",
                "verbose_name_plural": "Social Posts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SocialPostComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Social Post Comment",
                "verbose_name_plural": "Social Post Comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.AddField(
            model_name="socialpost",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="socialpost",
            name="likes",
            field=models.ManyToManyField(
                blank=True, related_name="liked_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="socialpostcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="socialpostcomment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="accounts.socialpost",
            ),
        ),
        migrations.AddIndex(
            model_name="socialpost",
            index=models.Index(
                fields=["-created_at"], name="accounts_so_created_27cd40_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="socialpost",
            index=models.Index(
                fields=["author", "-created_at"], name="accounts_so_author__ea2113_idx"
            ),
        ),
    ]
