# Generated by Django 5.0.1 on 2025-09-11 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_0004_merge_20250911_1821_0005_add_community'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('avatar', models.ImageField(blank=True, upload_to='profiles/')),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('emergency_contact', models.CharField(blank=True, max_length=100)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('is_public', models.BooleanField(default=False)),
                ('show_sobriety_date', models.BooleanField(default=False)),
                ('allow_messages', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='groupmembership',
            name='unique_group_membership',
        ),
        migrations.RemoveConstraint(
            model_name='recoverybuddy',
            name='unique_recovery_buddy',
        ),
        migrations.RemoveConstraint(
            model_name='sponsorrelationship',
            name='unique_sponsor_relationship',
        ),
        migrations.RemoveConstraint(
            model_name='userconnection',
            name='unique_user_connection',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='accounts_gr_user_id_9047d7_idx',
            old_name='accounts_gr_user_id_f8e7d6_idx',
        ),
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='accounts_gr_group_i_5ca2bd_idx',
            old_name='accounts_gr_group_i_e7d6c5_idx',
        ),
        migrations.RenameIndex(
            model_name='grouppost',
            new_name='accounts_gr_group_i_418380_idx',
            old_name='accounts_gr_group_i_f8e9a7_idx',
        ),
        migrations.RenameIndex(
            model_name='grouppost',
            new_name='accounts_gr_author__4d2d24_idx',
            old_name='accounts_gr_author__e9a7b8_idx',
        ),
        migrations.RenameIndex(
            model_name='recoverybuddy',
            new_name='accounts_re_user1_i_660865_idx',
            old_name='accounts_re_user1_i_e6f8b9_idx',
        ),
        migrations.RenameIndex(
            model_name='recoverybuddy',
            new_name='accounts_re_user2_i_a5e6f4_idx',
            old_name='accounts_re_user2_s_f9e8c7_idx',
        ),
        migrations.RenameIndex(
            model_name='recoverygroup',
            new_name='accounts_re_group_t_b4d078_idx',
            old_name='accounts_re_group_t_a8f7e6_idx',
        ),
        migrations.RenameIndex(
            model_name='recoverygroup',
            new_name='accounts_re_is_acti_527c90_idx',
            old_name='accounts_re_is_acti_f7e6d5_idx',
        ),
        migrations.RenameIndex(
            model_name='sponsorrelationship',
            new_name='accounts_sp_sponsor_92e57f_idx',
            old_name='accounts_sp_sponsor_bb79f8_idx',
        ),
        migrations.RenameIndex(
            model_name='sponsorrelationship',
            new_name='accounts_sp_sponsee_e23a73_idx',
            old_name='accounts_sp_sponsee_a8f2e9_idx',
        ),
        migrations.RenameIndex(
            model_name='userconnection',
            new_name='accounts_us_followe_89cfc9_idx',
            old_name='accounts_us_followe_b4c8b5_idx',
        ),
        migrations.RenameIndex(
            model_name='userconnection',
            new_name='accounts_us_followi_39070f_idx',
            old_name='accounts_us_followi_7c8f9e_idx',
        ),
        migrations.AlterUniqueTogether(
            name='groupmembership',
            unique_together={('user', 'group')},
        ),
        migrations.AlterUniqueTogether(
            name='recoverybuddy',
            unique_together={('user1', 'user2')},
        ),
        migrations.AlterUniqueTogether(
            name='sponsorrelationship',
            unique_together={('sponsor', 'sponsee')},
        ),
        migrations.AlterUniqueTogether(
            name='userconnection',
            unique_together={('follower', 'following', 'connection_type')},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
