# Generated by Django 5.0.1 on 2025-12-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_grouppostcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('pal_request', 'Recovery Pal Request'), ('pal_accepted', 'Pal Request Accepted'), ('message', 'New Message'), ('follow', 'New Follower'), ('sponsor_request', 'Sponsor Request'), ('sponsor_accepted', 'Sponsor Request Accepted'), ('challenge_invite', 'Challenge Invitation'), ('challenge_pal', 'Challenge Pal Request'), ('milestone', 'Milestone Achievement'), ('group_invite', 'Group Invitation'), ('group_post', 'New Group Post'), ('group_comment', 'New Group Comment'), ('group_join', 'New Group Member'), ('comment', 'New Comment'), ('like', 'New Like')], max_length=20),
        ),
        migrations.AlterField(
            model_name='socialpost',
            name='content',
            field=models.TextField(blank=True, help_text='Share your thoughts, wins, or encouragement'),
        ),
        migrations.AddIndex(
            model_name='grouppostcomment',
            index=models.Index(fields=['post', 'created_at'], name='accounts_gr_post_id_ad2ff6_idx'),
        ),
    ]
