# Generated by Django 5.0.1 on 2025-12-27 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_post_char_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.JSONField(blank=True, default=list, help_text="User's selected interests for matching"),
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_stage',
            field=models.CharField(blank=True, choices=[('starting', 'Just Starting (0-30 days)'), ('building', 'Building Foundation (1-6 months)'), ('growing', 'Growing Stronger (6-12 months)'), ('thriving', 'Thriving (1+ years)'), ('supporting', 'Supporting Others')], help_text='Where user is in their recovery journey', max_length=20, null=True),
        ),
    ]
