# Generated by Django 5.0.1 on 2025-12-27 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_post_reactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_checkin_reminder_sent',
            field=models.DateTimeField(blank=True, help_text='Last check-in reminder sent', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_weekly_digest_sent',
            field=models.DateTimeField(blank=True, help_text='Last weekly digest sent', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='welcome_email_1_sent',
            field=models.DateTimeField(blank=True, help_text='Welcome email Day 1 sent timestamp', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='welcome_email_2_sent',
            field=models.DateTimeField(blank=True, help_text='Welcome email Day 3 sent timestamp', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='welcome_email_3_sent',
            field=models.DateTimeField(blank=True, help_text='Welcome email Day 7 sent timestamp', null=True),
        ),
    ]
