# Generated by Django 5.0.1 on 2025-12-27 21:15

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_engagement_email_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ABTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('traffic_percentage', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'ab_tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ABTestVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('weight', models.IntegerField(default=1)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='accounts.abtest')),
            ],
            options={
                'db_table': 'ab_test_variants',
                'unique_together': {('test', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ABTestAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.abtest')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ab_test_assignments', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.abtestvariant')),
            ],
            options={
                'db_table': 'ab_test_assignments',
                'unique_together': {('user', 'test')},
            },
        ),
        migrations.CreateModel(
            name='ABTestConversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_type', models.CharField(choices=[('started_onboarding', 'Started Onboarding'), ('completed_step_1', 'Completed Step 1'), ('completed_step_2', 'Completed Step 2'), ('completed_step_3', 'Completed Step 3'), ('completed_step_4', 'Completed Step 4'), ('completed_step_5', 'Completed Step 5'), ('completed_onboarding', 'Completed Onboarding'), ('followed_user', 'Followed a User'), ('first_post', 'Made First Post'), ('first_checkin', 'First Check-in'), ('day_1_return', 'Returned Day 1'), ('day_7_return', 'Returned Day 7')], max_length=50)),
                ('converted_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversions', to='accounts.abtestassignment')),
            ],
            options={
                'db_table': 'ab_test_conversions',
                'unique_together': {('assignment', 'conversion_type')},
            },
        ),
    ]
