# Generated by Django 5.0.1 on 2026-01-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_ab_testing'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_pal_nudge_sent',
            field=models.DateTimeField(blank=True, help_text='Last accountability nudge sent for Recovery Pal', null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('pal_request', 'Recovery Pal Request'), ('pal_accepted', 'Pal Request Accepted'), ('message', 'New Message'), ('follow', 'New Follower'), ('sponsor_request', 'Sponsor Request'), ('sponsor_accepted', 'Sponsor Request Accepted'), ('challenge_invite', 'Challenge Invitation'), ('challenge_pal', 'Challenge Pal Request'), ('milestone', 'Milestone Achievement'), ('group_invite', 'Group Invitation'), ('group_post', 'New Group Post'), ('group_comment', 'New Group Comment'), ('group_join', 'New Group Member'), ('comment', 'New Comment'), ('like', 'New Like'), ('meeting_reminder', 'Meeting Reminder'), ('pal_nudge', 'Recovery Pal Nudge')], max_length=20),
        ),
    ]
