# Generated by Django 5.0.1 on 2026-02-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_recoverycoachsession_coachmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_nudge_sent',
            field=models.DateTimeField(blank=True, help_text='Premium trial nudge email sent timestamp', null=True),
        ),
    ]
