# Generated by Django 5.0.1 on 2026-02-28 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_premium_nudge_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscription_source',
            field=models.CharField(choices=[('stripe', 'Stripe (Web)'), ('apple', 'Apple (iOS IAP)'), ('manual', 'Manual')], default='stripe', max_length=10),
        ),
    ]
