# Generated by Django 5.0.1 on 2026-03-03 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_add_subscription_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='linked_checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='social_posts', to='accounts.dailycheckin'),
        ),
    ]
