# Generated by Django 5.0.1 on 2026-04-06 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_add_activityfeed_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyRecoveryThought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author_attribution', models.CharField(blank=True, max_length=200)),
                ('reflection_prompt', models.CharField(blank=True, max_length=300)),
                ('date', models.DateField(db_index=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='pledge_taken',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dailycheckin',
            name='pledge_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
