# Generated by Django 5.0.1 on 2026-04-06 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_daily_thought_and_pledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecode',
            name='role',
            field=models.CharField(choices=[('general', 'General'), ('sponsor', 'Sponsor'), ('pal', 'Recovery Pal')], default='general', help_text='Relationship to create when invitee registers', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='recovery_start_date',
            field=models.DateField(blank=True, help_text='Original date recovery journey began. Never resets on relapse.', null=True),
        ),
        migrations.CreateModel(
            name='RelapseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relapse_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('substance', models.CharField(blank=True, max_length=100)),
                ('trigger', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relapse_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-relapse_date'],
                'indexes': [models.Index(fields=['user', '-relapse_date'], name='accounts_re_user_id_1e19fa_idx')],
            },
        ),
    ]
