# Generated by Django 5.0.1 on 2026-04-15 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_alter_notification_notification_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days', models.PositiveIntegerField()),
                ('style', models.CharField(default='classic', max_length=32)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('time_format', models.CharField(default='auto', max_length=16)),
                ('text_y', models.PositiveSmallIntegerField(default=50)),
                ('font_size', models.PositiveSmallIntegerField(default=110)),
                ('color', models.CharField(default='white', max_length=16)),
                ('outline', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_badges', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='accounts_sa_user_id_ffef52_idx')],
            },
        ),
    ]
