# Generated by Django 5.0.1 on 2026-05-23 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_rename_pro_to_court'),
        ('support_services', '0002_add_meeting_reminder_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourtReportProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=200)),
                ('case_number', models.CharField(blank=True, max_length=80)),
                ('court_name', models.CharField(blank=True, max_length=200)),
                ('jurisdiction', models.CharField(blank=True, help_text='State, county, or city', max_length=120)),
                ('judge_name', models.CharField(blank=True, max_length=120)),
                ('probation_officer_name', models.CharField(blank=True, max_length=120)),
                ('probation_officer_email', models.EmailField(blank=True, max_length=254)),
                ('attorney_email', models.EmailField(blank=True, max_length=254)),
                ('required_meetings_per_week', models.PositiveIntegerField(default=3)),
                ('report_period_start', models.DateField(blank=True, help_text='Start date the user is required to track from (e.g. sentencing date).', null=True)),
                ('report_period_end', models.DateField(blank=True, help_text='End date of compliance requirement (e.g. next court date or probation end).', null=True)),
                ('auto_email_monthly', models.BooleanField(default=False, help_text='Phase 2 — automatically email a monthly report to the probation officer.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='court_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Court Report Profile',
                'verbose_name_plural': 'Court Report Profiles',
                'db_table': 'court_report_profiles',
            },
        ),
        migrations.CreateModel(
            name='CourtReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('pdf', models.FileField(blank=True, null=True, upload_to='court/reports/')),
                ('pdf_hash', models.CharField(db_index=True, help_text='SHA-256 of the PDF bytes', max_length=64)),
                ('attendance_count', models.PositiveIntegerField(default=0)),
                ('legal_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('case_number_snapshot', models.CharField(blank=True, max_length=80)),
                ('court_name_snapshot', models.CharField(blank=True, max_length=200)),
                ('emailed_to', models.TextField(blank=True, help_text='Comma-separated recipients')),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Court Report',
                'verbose_name_plural': 'Court Reports',
                'db_table': 'court_reports',
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['user', '-generated_at'], name='court_repor_user_id_072966_idx'), models.Index(fields=['pdf_hash'], name='court_repor_pdf_has_b87aaf_idx')],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_name', models.CharField(max_length=200)),
                ('meeting_date', models.DateTimeField()),
                ('meeting_end_time', models.DateTimeField(blank=True, null=True)),
                ('meeting_address', models.CharField(blank=True, max_length=300)),
                ('meeting_online', models.BooleanField(default=False)),
                ('meeting_platform', models.CharField(blank=True, help_text='Zoom, online group AA, etc. — only when meeting_online=True.', max_length=80)),
                ('program', models.CharField(choices=[('aa', 'Alcoholics Anonymous'), ('na', 'Narcotics Anonymous'), ('ca', 'Cocaine Anonymous'), ('ma', 'Marijuana Anonymous'), ('ga', 'Gamblers Anonymous'), ('smart', 'SMART Recovery'), ('refuge', 'Refuge Recovery'), ('lifering', 'LifeRing'), ('other', 'Other Recovery Program')], default='aa', max_length=20)),
                ('meeting_type', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('discussion', 'Discussion'), ('speaker', 'Speaker'), ('step', 'Step Study'), ('big_book', 'Big Book Study'), ('beginners', 'Beginners / Newcomers'), ('mens', "Men's"), ('womens', "Women's"), ('lgbtq', 'LGBTQ+'), ('other', 'Other')], default='open', max_length=20)),
                ('verification_method', models.CharField(choices=[('self', 'Self-Reported'), ('signature', 'Digital Chair Signature'), ('photo', 'Photo of Attendance Card'), ('gps', 'GPS Verified'), ('qr', 'QR Code Check-In')], default='self', max_length=20)),
                ('chair_signature_name', models.CharField(blank=True, max_length=120)),
                ('chair_signature_at', models.DateTimeField(blank=True, null=True)),
                ('gps_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('gps_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('attendance_photo', models.ImageField(blank=True, null=True, upload_to='court/attendance/')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances', to='support_services.meeting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Meeting Attendance',
                'verbose_name_plural': 'Meeting Attendances',
                'db_table': 'meeting_attendances',
                'ordering': ['-meeting_date'],
                'indexes': [models.Index(fields=['user', '-meeting_date'], name='meeting_att_user_id_6f52dd_idx')],
            },
        ),
    ]
