# Generated by Django 5.0.1 on 2026-06-03 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_user_marketing_emails_enabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColdOutreachSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('source', models.CharField(blank=True, choices=[('sober_living', 'Sober Living'), ('rehab', 'Rehab / Treatment Center'), ('court_liaison', 'Court / Probation Liaison'), ('other', 'Other')], help_text='Which outreach list this address came from, if known.', max_length=20)),
                ('unsubscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cold-outreach opt-out',
                'verbose_name_plural': 'Cold-outreach opt-outs',
                'ordering': ['-unsubscribed_at'],
            },
        ),
    ]
