# Generated by Django 5.0.1 on 2026-06-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_coldoutreachsuppression'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('court', 'Court Compliance'), ('supporter', 'Supporter')], default='free', max_length=10),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium'), ('court', 'Court Compliance'), ('supporter', 'Supporter')], max_length=10),
        ),
    ]
