# Generated by Django 5.0.1 on 2026-06-11 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_add_supporter_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupporterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preset', models.CharField(choices=[('cheerleader', 'Cheerleader'), ('standard', 'Standard'), ('close', 'Close support')], default='standard', max_length=12)),
                ('status', models.CharField(choices=[('pending', 'Pending consent'), ('active', 'Active'), ('paused', 'Paused'), ('revoked', 'Revoked'), ('declined', 'Declined')], default='pending', max_length=10)),
                ('initiated_by', models.CharField(choices=[('member', 'Member'), ('supporter', 'Supporter')], max_length=10)),
                ('invite_email', models.EmailField(blank=True, max_length=254)),
                ('invite_token', models.CharField(blank=True, db_index=True, max_length=64)),
                ('inactivity_threshold_days', models.PositiveSmallIntegerField(default=3)),
                ('last_inactivity_alert_sent', models.DateTimeField(blank=True, null=True)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(help_text='Person in recovery whose progress is shared.', on_delete=django.db.models.deletion.CASCADE, related_name='supporter_links', to=settings.AUTH_USER_MODEL)),
                ('supporter', models.ForeignKey(help_text='Viewer; needs an active supporter subscription to see data.', on_delete=django.db.models.deletion.CASCADE, related_name='supporting_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Supporter Link',
                'verbose_name_plural': 'Supporter Links',
                'db_table': 'supporter_links',
                'indexes': [models.Index(fields=['member', 'status'], name='supporter_l_member__f8a6c2_idx'), models.Index(fields=['supporter', 'status'], name='supporter_l_support_c523d9_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='supporterlink',
            constraint=models.UniqueConstraint(fields=('member', 'supporter'), name='unique_member_supporter'),
        ),
    ]
