# Generated by Django 5.0.1 on 2026-06-11 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_supporter_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('pal_request', 'Recovery Pal Request'), ('pal_accepted', 'Pal Request Accepted'), ('message', 'New Message'), ('follow', 'New Follower'), ('sponsor_request', 'Sponsor Request'), ('sponsor_accepted', 'Sponsor Request Accepted'), ('challenge_invite', 'Challenge Invitation'), ('challenge_pal', 'Challenge Pal Request'), ('milestone', 'Milestone Achievement'), ('group_invite', 'Group Invitation'), ('group_post', 'New Group Post'), ('group_comment', 'New Group Comment'), ('group_join', 'New Group Member'), ('comment', 'New Comment'), ('like', 'New Like'), ('meeting_reminder', 'Meeting Reminder'), ('pal_nudge', 'Recovery Pal Nudge'), ('new_blog_post', 'New Blog Post'), ('checkin_reminder', 'Check-in Reminder'), ('supporter_request', 'Supporter Request'), ('supporter_consented', 'Supporter Connected'), ('supporter_encouragement', 'Encouragement from Supporter'), ('member_support_request', 'Member Asked for Support'), ('member_inactive', 'Member Inactivity Alert')], max_length=30),
        ),
    ]
