# Generated by Django 5.0.1 on 2026-06-11 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_supporter_nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supporterlink',
            name='supporter',
            field=models.ForeignKey(blank=True, help_text='Viewer; null until an email invitee accepts. Needs active supporter sub to view.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supporting_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
