# Generated by Django 5.0.1 on 2026-06-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_seed_supporter_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='support_circle_email_sent_at',
            field=models.DateTimeField(blank=True, help_text='Support Circle announcement email sent timestamp', null=True),
        ),
    ]
