# Generated by Django 5.0.1 on 2026-06-12 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_reset_trials'),
    ]

    operations = [
        migrations.AddField(
            model_name='recoverycoachsession',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual'), ('checkin_support', 'Check-in support')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='recoverycoachsession',
            name='triggering_checkin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coach_sessions', to='accounts.dailycheckin'),
        ),
    ]
