# Generated by Django 5.0.1 on 2026-06-15 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_recoverycoachsession_trigger_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='winback_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
