# Generated by Django 5.0.1 on 2026-06-18 17:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_reprice_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused')], default='active', max_length=10)),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Record-keeping only; billing is handled offline.', max_digits=8, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'facilities',
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='FacilityInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('uses', models.IntegerField(default=0)),
                ('max_uses', models.IntegerField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_facility_invites', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='accounts.facility')),
            ],
            options={
                'db_table': 'facility_invites',
            },
        ),
        migrations.CreateModel(
            name='FacilityMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('active', 'Active'), ('revoked', 'Revoked'), ('left', 'Left')], default='invited', max_length=10)),
                ('consent_granted_at', models.DateTimeField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(blank=True, null=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('risk_notified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accounts.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facility_memberships',
                'unique_together': {('facility', 'user')},
            },
        ),
        migrations.CreateModel(
            name='FacilityStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('coordinator', 'Coordinator')], default='coordinator', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='accounts.facility')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facility_staff_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'facility_staff',
                'unique_together': {('facility', 'user')},
            },
        ),
    ]
