# Generated by Django 5.0.1 on 2026-06-19 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_facility_facilityinvite_facilitymembership_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='activation_token',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='facility',
            name='email_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='facility',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused')], default='active', max_length=10),
        ),
    ]
