# Generated by Django 5.0.1 on 2026-06-19 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_facility_activation_token_facility_email_verified_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='milestone_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days sober celebrated by a milestone post', null=True),
        ),
        migrations.AddField(
            model_name='socialpost',
            name='post_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('milestone', 'Milestone')], default='standard', max_length=12),
        ),
    ]
