# Generated by Django 5.0.1 on 2026-07-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_dailypledge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pledge_photo',
            field=models.ImageField(blank=True, help_text='Optional photo shown on your daily pledge card.', null=True, upload_to='pledge_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='pledge_reason',
            field=models.CharField(blank=True, help_text="A short reason you're staying sober, e.g. 'my daughter'. Shown on your daily pledge.", max_length=120),
        ),
    ]
