# Generated by Django 5.0.1 on 2026-07-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_user_pledge_photo_user_pledge_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text='IANA timezone (e.g. America/Chicago), auto-detected from the browser.', max_length=64),
        ),
    ]
