# Generated by Django 5.0.1 on 2026-07-04 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailycheckin',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='dailypledge',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
