# Generated by Django 5.0.1 on 2026-07-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_alter_dailycheckin_date_alter_dailypledge_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailypledge',
            name='note',
            field=models.CharField(blank=True, default='', help_text="Optional reflection attached to today's pledge.", max_length=280),
        ),
        migrations.AddField(
            model_name='dailypledge',
            name='photo',
            field=models.ImageField(blank=True, help_text="Optional photo attached to today's pledge.", null=True, upload_to='pledge_photos/'),
        ),
    ]
