# Generated by Django 5.0.1 on 2026-07-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0058_dailypledge_note_dailypledge_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_email_2_sent',
            field=models.DateTimeField(blank=True, help_text='Onboarding E2 (Anchor, day 1) sent/skipped timestamp', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_email_3_sent',
            field=models.DateTimeField(blank=True, help_text='Onboarding E3 (journal, day 3) sent/skipped timestamp', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_email_4_sent',
            field=models.DateTimeField(blank=True, help_text='Onboarding E4 (community, day 6) sent/skipped timestamp', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_email_5_sent',
            field=models.DateTimeField(blank=True, help_text='Onboarding E5 (milestone, day 9) sent/skipped timestamp', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_email_6_sent',
            field=models.DateTimeField(blank=True, help_text='Onboarding E6 (check-in, day 14) sent/skipped timestamp', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reengagement_email_1_sent',
            field=models.DateTimeField(blank=True, help_text='Re-engagement R1 (door open) sent timestamp', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reengagement_email_2_sent',
            field=models.DateTimeField(blank=True, help_text="Re-engagement R2 (what's new) sent timestamp", null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reengagement_email_3_sent',
            field=models.DateTimeField(blank=True, help_text='Re-engagement R3 (honest ask) sent timestamp', null=True),
        ),
    ]
