# Generated by Django 5.0.1 on 2026-07-09 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_user_email_sequence_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtreport',
            name='pdf_embedded_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 fingerprint printed inside the PDF', max_length=64),
        ),
    ]
