# Generated by Django 5.0.1 on 2026-07-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_courtreport_pdf_embedded_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtreport',
            name='pdf_data',
            field=models.BinaryField(blank=True, help_text='PDF bytes (canonical storage)', null=True),
        ),
    ]
