# Generated by Django 5.0.1 on 2026-07-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_courtreport_pdf_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='courtreportprofile',
            name='last_auto_po_email_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='courtreportprofile',
            name='last_meeting_reminder_sent',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='courtreportprofile',
            name='auto_email_monthly',
            field=models.BooleanField(default=False, help_text="On the 1st of each month, automatically generate last month's attendance report and email it to your probation officer.", verbose_name='Auto-email monthly report to my probation officer'),
        ),
    ]
