# Generated by Django 5.0.1 on 2026-07-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_courtreportprofile_last_auto_po_email_sent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recoverycoachsession',
            name='trigger',
            field=models.CharField(choices=[('manual', 'Manual'), ('checkin_support', 'Check-in support'), ('sos', 'Craving SOS')], default='manual', max_length=20),
        ),
    ]
