# Generated by Django 5.0.1 on 2026-07-11 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_recoverycoachsession_trigger'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelapsePreventionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggers', models.TextField(blank=True, help_text='People, places, feelings that put you at risk')),
                ('warning_signs', models.TextField(blank=True, help_text="Early signs you're drifting toward a slip")),
                ('coping_strategies', models.TextField(blank=True, help_text='What actually works when a craving hits')),
                ('reasons', models.TextField(blank=True, help_text='Your reasons for recovery')),
                ('emergency_steps', models.TextField(blank=True, help_text='Exact steps if a slip happens or feels close')),
                ('halt_notes', models.TextField(blank=True, help_text='HALT: how hunger, anger, loneliness, tiredness show up for you')),
                ('support_contacts', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relapse_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
