# Generated by Django 5.0.1 on 2026-07-13 13:44

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_relapsepreventionplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='socialpost',
            name='video',
            field=models.FileField(blank=True, null=True, storage=apps.accounts.models._social_post_video_storage, upload_to='social_posts/videos/'),
        ),
    ]
