# Generated by Django 5.0.1 on 2026-09-26 14:55

import apps.accounts.medallion_models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0066_medallion_pack_purchase'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeepsakeOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.accounts.medallion_models._new_token, max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('amount_cents', models.PositiveIntegerField(default=0)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('receipt_emailed', models.BooleanField(default=False)),
                ('days', models.PositiveIntegerField()),
                ('style', models.CharField(max_length=30)),
                ('name', models.CharField(blank=True, max_length=30)),
                ('time_format', models.CharField(default='auto', max_length=10)),
                ('font_size', models.PositiveIntegerField(default=110)),
                ('color', models.CharField(default='white', max_length=10)),
                ('outline', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('product', models.CharField(choices=[('mug', 'Mug'), ('sticker', 'Sticker')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Awaiting payment'), ('paid', 'Paid'), ('submitted', 'Sent to printer'), ('in_production', 'In production'), ('shipped', 'Shipped'), ('failed', 'Needs attention'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('shipping_name', models.CharField(blank=True, max_length=200)),
                ('shipping_phone', models.CharField(blank=True, max_length=40)),
                ('shipping_address', models.JSONField(blank=True, default=dict)),
                ('printify_order_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('tracking_url', models.URLField(blank=True, max_length=500)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('carrier', models.CharField(blank=True, max_length=50)),
                ('last_error', models.TextField(blank=True)),
                ('shipped_emailed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='keepsake_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
