# Generated by Django 5.0.1 on 2026-09-26 18:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0067_keepsake_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingattendance',
            name='chair_confirm_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='chair_confirm_token',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='chair_confirm_user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='chair_role',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='meetingattendance',
            name='qr_shown_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CourtReportPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount_cents', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('refunded', 'Refunded')], default='pending', max_length=10)),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_payment_intent_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase', to='accounts.courtreport')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='court_report_purchases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
