# Generated by Django 5.0.1 on 2026-09-26 18:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0068_court_single_report_and_chair_qr'),
    ]

    operations = [
        migrations.AddField(
            model_name='supporterlink',
            name='invite_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='supporterlink',
            name='loved_one_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='supporterlink',
            name='member',
            field=models.ForeignKey(blank=True, help_text='Person in recovery whose progress is shared. Null only while a family-started (supporter-initiated) invite awaits their consent.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporter_links', to=settings.AUTH_USER_MODEL),
        ),
    ]
