# Generated by Django 5.0.1 on 2026-09-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0070_hide_private_checkin_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='revenuecat_app_user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
