# Generated by Django 5.2.17 on 2026-10-04 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0073_announcement_delivery"),
    ]

    operations = [
        migrations.AlterField(
            model_name="abtestconversion",
            name="conversion_type",
            field=models.CharField(
                choices=[
                    ("started_onboarding", "Started Onboarding"),
                    ("completed_step_1", "Completed Step 1"),
                    ("completed_step_2", "Completed Step 2"),
                    ("completed_step_3", "Completed Step 3"),
                    ("completed_step_4", "Completed Step 4"),
                    ("completed_step_5", "Completed Step 5"),
                    ("completed_onboarding", "Completed Onboarding"),
                    ("followed_user", "Followed a User"),
                    ("first_post", "Made First Post"),
                    ("first_checkin", "First Check-in"),
                    ("day_1_return", "Returned Day 1"),
                    ("day_7_return", "Returned Day 7"),
                    ("started_trial", "Started a Premium trial"),
                    ("began_checkout", "Opened Premium checkout"),
                    ("subscribed", "Subscribed (card on file or Apple)"),
                    ("converted_paid", "First real payment"),
                ],
                max_length=50,
            ),
        ),
    ]
