# Generated by Django 5.0.1 on 2026-05-15 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-is_featured', '-created_at']},
        ),
        migrations.AddField(
            model_name='product',
            name='external_url',
            field=models.URLField(default='', help_text='The buy link — Printify product page or Amazon listing.', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured products are shown first.'),
        ),
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(choices=[('printify', 'Printify'), ('amazon_kdp', 'Amazon KDP'), ('other', 'Other')], default='printify', help_text='Where the product is sold. Controls the badge and button label.', max_length=20),
        ),
    ]
