# Generated by Django 5.0.1 on 2026-05-26 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_product_options_product_external_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneEmailSent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_days', models.IntegerField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milestone_emails_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Milestone Email Sent',
                'verbose_name_plural': 'Milestone Emails Sent',
                'indexes': [models.Index(fields=['user', 'milestone_days'], name='store_miles_user_id_e278b3_idx')],
                'unique_together': {('user', 'milestone_days')},
            },
        ),
    ]
