# Generated by Django 5.0.1 on 2025-10-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(help_text='Rich text content - HTML allowed'),
        ),
    ]
