# Generated by Django 5.2.4 on 2025-07-12 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('prompt', models.TextField(help_text='The question or prompt for the user')),
                ('category', models.CharField(choices=[('gratitude', 'Gratitude'), ('reflection', 'Daily Reflection'), ('goals', 'Goals & Aspirations'), ('triggers', 'Triggers & Challenges'), ('coping', 'Coping Strategies'), ('milestones', 'Milestones & Progress'), ('relationships', 'Relationships'), ('self_care', 'Self Care'), ('emotions', 'Emotional Check-in')], max_length=20)),
                ('stage', models.CharField(choices=[('early', 'Early Recovery (0-30 days)'), ('middle', 'Sustained Recovery (31-365 days)'), ('ongoing', 'Ongoing Recovery (1+ years)'), ('all', 'All Stages')], default='all', help_text='Recovery stage this prompt is most relevant for', max_length=20)),
                ('follow_up_1', models.TextField(blank=True, help_text='Optional follow-up question')),
                ('follow_up_2', models.TextField(blank=True, help_text='Optional second follow-up')),
                ('min_days_sober', models.IntegerField(default=0, help_text='Minimum days sober to see this prompt')),
                ('max_days_sober', models.IntegerField(blank=True, help_text='Maximum days sober (leave blank for no limit)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'min_days_sober'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='Optional title for your entry', max_length=200)),
                ('content', models.TextField()),
                ('mood_rating', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='How are you feeling today? (1=lowest, 10=highest)', null=True)),
                ('gratitude_1', models.CharField(blank=True, help_text="Something you're grateful for", max_length=200)),
                ('gratitude_2', models.CharField(blank=True, max_length=200)),
                ('gratitude_3', models.CharField(blank=True, max_length=200)),
                ('cravings_today', models.BooleanField(default=False, help_text='Did you experience cravings today?')),
                ('craving_intensity', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], help_text='If yes, how intense? (1=mild, 10=severe)', null=True)),
                ('is_private', models.BooleanField(default=True, help_text='Keep this entry private')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to=settings.AUTH_USER_MODEL)),
                ('prompt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='journal.journalprompt')),
            ],
            options={
                'verbose_name_plural': 'Journal entries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField(help_text='Time to send daily reminder')),
                ('is_active', models.BooleanField(default=True)),
                ('monday', models.BooleanField(default=True)),
                ('tuesday', models.BooleanField(default=True)),
                ('wednesday', models.BooleanField(default=True)),
                ('thursday', models.BooleanField(default=True)),
                ('friday', models.BooleanField(default=True)),
                ('saturday', models.BooleanField(default=True)),
                ('sunday', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_reminders', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JournalStreak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_streak', models.IntegerField(default=0)),
                ('longest_streak', models.IntegerField(default=0)),
                ('last_entry_date', models.DateField(blank=True, null=True)),
                ('total_entries', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_streak', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
