# Generated by Django 5.0.1 on 2026-01-10 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookmark',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userbookmark',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
