# Generated by Django 5.0.1 on 2026-09-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_services', '0002_add_meeting_reminder_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverageRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=120, unique=True)),
                ('postal_code', models.CharField(blank=True, db_index=True, max_length=10)),
                ('hits', models.PositiveIntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(default=False, help_text='Tick once a feed covering this area has been added.')),
            ],
            options={
                'verbose_name': 'coverage request',
                'ordering': ['-hits', '-last_seen'],
            },
        ),
    ]
