# Generated by Django 5.0.1 on 2026-09-26 18:07

import apps.support_services.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_services', '0003_coveragerequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('token', models.CharField(default=apps.support_services.models._reminder_token, max_length=64, unique=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='support_services.meeting')),
            ],
            options={
                'indexes': [models.Index(fields=['confirmed_at'], name='support_ser_confirm_e78cc5_idx')],
                'unique_together': {('email', 'meeting')},
            },
        ),
    ]
