# Generated by Django 5.0.1 on 2026-09-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_services', '0004_meeting_reminder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='conference_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
