# Generated by Django 5.0.1 on 2025-07-17 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='difficulty_level',
            field=models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='estimated_time',
            field=models.CharField(blank=True, help_text='Estimated time to complete (e.g., "10 minutes")', max_length=50),
        ),
        migrations.AddField(
            model_name='resource',
            name='interaction_type',
            field=models.CharField(choices=[('static', 'Static Content'), ('interactive', 'Interactive Tool'), ('hybrid', 'Both Static and Interactive')], default='static', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='interactive_component',
            field=models.CharField(blank=True, help_text='Name of the React/JS component for interactive resources', max_length=100),
        ),
        migrations.AddField(
            model_name='resource',
            name='is_interactive',
            field=models.BooleanField(default=False, help_text='Does this resource have an interactive component?'),
        ),
        migrations.AddField(
            model_name='resourcetype',
            name='icon',
            field=models.CharField(blank=True, help_text='Emoji icon for this resource type', max_length=10),
        ),
        migrations.CreateModel(
            name='InteractiveResourceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_data', models.JSONField(default=dict, help_text='Store session-specific data (e.g., checked items)')),
                ('completed_items', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('completion_percentage', models.FloatField(default=0.0)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactive_progress', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_updated'],
            },
        ),
        migrations.CreateModel(
            name='ResourceUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'Viewed'), ('download', 'Downloaded'), ('complete', 'Completed'), ('interact', 'Used Interactive')], max_length=20)),
                ('duration', models.DurationField(blank=True, help_text='Time spent on resource', null=True)),
                ('completed', models.BooleanField(default=False)),
                ('progress_data', models.JSONField(blank=True, default=dict, help_text='Store progress data for interactive resources')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='resources.resource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
