# Generated by Django 5.2.17 on 2026-10-03 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0004_program_enrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="programenrollment",
            name="last_email_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programenrollment",
            name="last_reminder_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="programenrollment",
            name="premium_nudge_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="programenrollment",
            name="reminders_enabled",
            field=models.BooleanField(default=True),
        ),
    ]
