# Generated by Django 5.2.17 on 2026-10-03 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0072_notification_program_reminder"),
        ("resources", "0005_program_reminders"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgramCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_slug", models.SlugField(max_length=60)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "group",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="program_cohort",
                        to="accounts.recoverygroup",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="programenrollment",
            name="cohort",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="enrollments",
                to="resources.programcohort",
            ),
        ),
    ]
