# Generated by Django 5.2.17 on 2026-10-03 18:02

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0006_program_cohort"),
    ]

    operations = [
        migrations.CreateModel(
            name="AudioTrack",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("category", models.CharField(max_length=30)),
                ("description", models.TextField(blank=True)),
                ("is_free", models.BooleanField(default=False)),
                ("reflection_slug", models.SlugField(blank=True, max_length=60)),
                ("transcript", models.TextField(blank=True)),
                (
                    "audio",
                    models.FileField(
                        storage=resources.models._audio_storage,
                        upload_to=resources.models._audio_upload_to,
                    ),
                ),
                ("duration_seconds", models.FloatField(default=0)),
                ("content_hash", models.CharField(blank=True, max_length=64)),
                ("voice_id", models.CharField(blank=True, max_length=64)),
                ("model_id", models.CharField(blank=True, max_length=64)),
                ("is_active", models.BooleanField(default=True)),
                ("generated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "title"],
            },
        ),
    ]
