# Generated by Django 5.2.17 on 2026-10-03 22:46

import resources.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("resources", "0007_audio_track"),
    ]

    operations = [
        migrations.AddField(
            model_name="audiotrack",
            name="preview",
            field=models.FileField(
                blank=True,
                storage=resources.models._audio_storage,
                upload_to=resources.models._preview_upload_to,
            ),
        ),
        migrations.AddField(
            model_name="audiotrack",
            name="preview_seconds",
            field=models.FloatField(default=0),
        ),
    ]
