# Generated by Django 5.0.1 on 2025-09-11 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20250911_1821'),
        ('accounts', '0005_add_community'),
    ]

    operations = [
    ]
