# Generated by Django 5.0.1 on 2025-09-13 00:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_challengebadge_challengecheckin_challengecomment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupchallenge',
            old_name='allow_buddy_system',
            new_name='allow_pal_system',
        ),
        migrations.AlterField(
            model_name='challengeparticipant',
            name='accountability_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pal_partnerships', to='accounts.challengeparticipant'),
        ),
        migrations.CreateModel(
            name='RecoveryPal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='pending', max_length=20)),
                ('started_date', models.DateField(blank=True, null=True)),
                ('ended_date', models.DateField(blank=True, null=True)),
                ('check_in_frequency', models.CharField(blank=True, help_text='How often you want to check in with each other', max_length=50)),
                ('shared_goals', models.TextField(blank=True, help_text='Shared recovery goals and commitments')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pal_relationships_as_user1', to=settings.AUTH_USER_MODEL)),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pal_relationships_as_user2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RecoveryBuddy',
        ),
        migrations.AddIndex(
            model_name='recoverypal',
            index=models.Index(fields=['user1', 'status'], name='accounts_re_user1_i_e88f31_idx'),
        ),
        migrations.AddIndex(
            model_name='recoverypal',
            index=models.Index(fields=['user2', 'status'], name='accounts_re_user2_i_347cc2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recoverypal',
            unique_together={('user1', 'user2')},
        ),
    ]
